version: "3.5"


services:

  proxy:
    image: "traefik:v2.2"
    container_name: "proxy"
    command:
      # Uncomment two commands below for debugging information inside the proxy container logs(docker logs proxy):
      #- "--log.level=DEBUG"
      #- "--certificatesresolvers.proxyresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.proxyresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.proxyresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.proxyresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.proxyresolver.acme.storage=/letsencrypt/acme.json"
    networks:
      - proxy-network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - "CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}"
      - "CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}"
    volumes:
      - letsencrypt:/letsencrypt
      - traefik-conf:/etc/traefik/conf
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      ## DNS CHALLENGE
      - "traefik.http.routers.traefik.tls.certresolver=proxyresolver"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.${YOUR_DOMAIN}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=${YOUR_DOMAIN}"
      ## TRAEFIC DASHBOARD 
      - "traefik.http.routers.traefik-dashboard.rule=Host(`proxy.${YOUR_DOMAIN}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=proxyresolver"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.traefik-dashboard-auth.basicauth.usersfile=/etc/traefik/conf/htpasswd"
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-dashboard-auth@docker"


networks:

  proxy-network:
    name: proxy-network
    driver: bridge


volumes:

    traefik-conf:
      driver_opts:
        type: none
        device: ${TRAEFIK_CONFIG}
        o: bind

    letsencrypt:
      driver_opts:
        type: none
        device: ${TRAEFIK_LETSENCRYPT}
        o: bind